name: Start

on:
  push:
  gollum:
  schedule:
    - cron: "30 22 * * *"

jobs:
  sign-in:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Build and Run
        env:
          BDUSS: ${{ secrets.BDUSS }}
        run: |
          cargo build --release
          cargo r --release
        working-directory: ./sign-in
