name: Start

on:
  push:
  gollum:
  schedule:
    - cron: "30 22 * * *"

jobs:
  sign-in:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v1

      - name: Build and Run
        env:
          BDUSS: ${{ secrets.BDUSS }}
        run: |
          cargo build --release
          cargo run --release
